//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift open source project
//
// Copyright (c) 2025-2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://swift.org/LICENSE.txt for license information
// See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import SWBCSupport
import SWBProtocol
public import SWBUtil
public import SWBMacro
import Foundation           // For NSRegularExpression.Options

/// Information to be propagated to consumers of a diagnostic generated by `libclang` so they can perform actions in response to it..
public struct LibclangDiagnosticAttachmentInfo: SerializableCodable, Sendable {
    /// If a module error was seen, then Xcode may delete the module directories at these paths.
    let pathsToDeleteOnModuleError: [Path]

    /// Return a default instance based on the given parameters.
    public static func attachmentInfo(scope: MacroEvaluationScope) -> LibclangDiagnosticAttachmentInfo {
        let pathsToDeleteOnModuleError = [
            BuiltinMacros.MODULE_CACHE_DIR,
            BuiltinMacros.CLANG_EXPLICIT_MODULES_OUTPUT_PATH,
            BuiltinMacros.SWIFT_EXPLICIT_MODULES_OUTPUT_PATH,
        ].compactMap {
            scope.evaluate($0).nilIfEmpty
        }
        let uniquePathsToDeleteOnModuleError = OrderedSet(pathsToDeleteOnModuleError).elements

        // FIXME: We should unique these values (but preserve their order).
        return LibclangDiagnosticAttachmentInfo(pathsToDeleteOnModuleError: uniquePathsToDeleteOnModuleError)
    }
}

let moduleErrorRegexes: [RegEx] = [
    RegEx(patternLiteral: "^.*file '.*' has been modified since the module file '.*' was built: .*$", options: .anchorsMatchLines),
    RegEx(patternLiteral: "^.*please rebuild precompiled file .*$", options: .anchorsMatchLines),
    RegEx(patternLiteral: "^.*precompiled file '.*' needs to be rebuilt.*$", options: .anchorsMatchLines),
    RegEx(patternLiteral: "^.*module '.*' is needed but has not been provided, and implicit use of module files is disabled.*$", options: .anchorsMatchLines),
    RegEx(patternLiteral: "^.*module file '.*' is out of date and needs to be rebuilt: .*$", options: .anchorsMatchLines),
    RegEx(patternLiteral: "^.*module '.*' is defined in both '.*' and '.*'.*$", options: .anchorsMatchLines),
    RegEx(patternLiteral: "^.*unexpected variant during dependency scanning on module '.*'.*$", options: .anchorsMatchLines),
]

extension Diagnostic {
    public init(_ diagnostic: ClangDiagnostic, workingDirectory: Path, appendToOutputStream: Bool, attachmentInfo: LibclangDiagnosticAttachmentInfo?) {
        // Examine the message test to see whether it contains any traits we want to record or attachments we want to add.
        var traits = Set<String>()
        var attachments = [String: Attachment]()
        if diagnostic.severity == .error || diagnostic.severity == .fatal {
            for regex in moduleErrorRegexes {
                if regex.firstMatch(in: diagnostic.text) != nil {
                    let trait = BuildOperationDiagnosticTrait.moduleError.rawValue
                    traits.insert(trait)
                    attachments[trait] = DiagnosticAttachments.ModuleErrorAttachment(pathsToDelete: attachmentInfo?.pathsToDeleteOnModuleError.map({ $0.str }) ?? [])
                    break
                }
            }
        }

        self.init(behavior: .init(diagnostic.severity), location: diagnostic.fileName.map { path in .path((Path(path).makeAbsolute(relativeTo: workingDirectory) ?? Path(path)).normalize(), line: Int(diagnostic.line), column: Int(diagnostic.column)) } ?? .unknown, sourceRanges: diagnostic.ranges.map { .init($0) }, data: DiagnosticData(diagnostic.text, component: diagnostic.categoryText.map { .clangCompiler(categoryName: $0) } ?? .default, optionName: diagnostic.optionName), appendToOutputStream: appendToOutputStream, fixIts: diagnostic.fixIts.map { .init($0) }, traits: traits, attachments: attachments, childDiagnostics: diagnostic.childDiagnostics.map { .init($0, workingDirectory: workingDirectory, appendToOutputStream: appendToOutputStream, attachmentInfo: attachmentInfo) })
    }
}

extension Diagnostic.SourceRange {
    public init(_ range: ClangSourceRange) {
        self.init(path: Path(range.path), startLine: Int(range.startLine), startColumn: Int(range.startColumn), endLine: Int(range.endLine), endColumn: Int(range.endColumn))
    }
}

extension Diagnostic.FixIt {
    public init(_ fixIt: ClangFixIt) {
        self.init(sourceRange: .init(fixIt.range), newText: fixIt.text)
    }
}

extension Diagnostic.Behavior {
    public init(_ severity: ClangDiagnostic.Severity) {
        switch severity {
        case .ignored:
            self = .ignored
        case .note:
            self = .note
        case .warning:
            self = .warning
        case .error,
             .fatal:
            self = .error
        }
    }
}
